# Generated by Django 5.0.1 on 2024-02-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('b_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('b_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myfirstapp.books')),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myfirstapp.members')),
            ],
        ),
    ]
